apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: homeoffice-ui-run-
  namespace: quarkusdroneshop-cicd
  labels:
    app.kubernetes.io/name: quarkusdroneshop-homeoffice-ui
    tekton.dev/pipeline: build-and-push-quarkusdroneshop-homeoffice-ui
spec:
  pipelineRef:
    name: build-and-push-quarkusdroneshop-homeoffice-ui
  params:
    - name: git-url
      value: https://github.com/quarkusdroneshop/quarkusdroneshop-homeoffice-ui.git
    - name: git-revision
      value: main
    - name: image-name
      value: quay.io/quarkusdroneshop/quarkusdroneshop-homeoffice-ui
    - name: image-tag
      value: latest
    - name: base-url
      value: http://homeoffice-ui.quarkusdroneshop.svc.cluster.local:8080
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
