apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-homeoffice-ui
  description: バックヤード業務のUIサービスです
  labels:
    app: homeoffice-ui
  annotations:
    github.com/project-slug: quarkusdroneshop/quarkusdroneshop-homeoffice-ui
    backstage.io/kubernetes-id: quarkusdroneshop-homeoffice-ui
    backstage.io/kubernetes-cluster: sandbox1332
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-homeoffice-ui
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-homeoffice-ui
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
spec:
  type: web
  owner: user:default/nmushino
  lifecycle: production
  system: sandbox1332
  dependsOn:
    - component:quarkusdroneshop-homeoffice
